# ===================================================================
# Spring Cloud Config.
# ===================================================================

# Property used on app startup to check the config server status
configserver:
    name: Terminal Manager Config Service
    status: Connected to the Terminal Manager Registry config server.

jhipster:
    security:
        authentication:
            jwt:
                 secret: OTAwNDdkNDFkMGExYTFhNTlhODBmM2VlOTQ5MWEwOGExMjE4ZDUwYzRkNzZiNzU3YTgyOWJiMmEzNDIzYmZhZWQyMzVhZTBjNzA5OWY5ZTAxY2M4ZWU3MzE2NDhhNThhYTcyMmQ3OTNiOWY0NTFlNzgyNjhlYzhkMTBiZTY2YWE=
                 base64-secret: OTAwNDdkNDFkMGExYTFhNTlhODBmM2VlOTQ5MWEwOGExMjE4ZDUwYzRkNzZiNzU3YTgyOWJiMmEzNDIzYmZhZWQyMzVhZTBjNzA5OWY5ZTAxY2M4ZWU3MzE2NDhhNThhYTcyMmQ3OTNiOWY0NTFlNzgyNjhlYzhkMTBiZTY2YWE=
